---
title: "European Cars"
output: html_document
date: "2025-02-13"
---

```{r setup, include=FALSE}
#install.packages("psych")
#install.packages("corrplot")
library(corrplot)
library(psych)
library(tidyverse)
library(skimr)
library(dplyr)
```

## R Markdown

```{r}
EUcars <- read_csv("car_prices.csv", na = c("", NA, "N/A"))
EUcars = EUcars |> drop_na() |> filter (Brand == "Fiat", Gearbox != "Semi-automatic", Drivetrain != "Rear") |> select(Model,Price,Kilometers,Power, Seats,Doors,Cylinders,Gearbox,Year,Drivetrain,Country)

EUcars <- replace(EUcars, EUcars == "Automatic", "0")
EUcars <- replace(EUcars, EUcars == "Manual", "1")
EUcars <- replace(EUcars, EUcars == "4WD", "1")
EUcars <- replace(EUcars, EUcars == "Front", "0")
EUcars <- replace(EUcars, EUcars == "AT", "1")
EUcars <- replace(EUcars, EUcars == "BE", "2")
EUcars <- replace(EUcars, EUcars == "DE", "3")
EUcars <- replace(EUcars, EUcars == "IT", "4")
EUcars <- replace(EUcars, EUcars == "NL", "5")

EUcars$Gearbox = as.numeric(EUcars$Gearbox)
EUcars$Drivetrain = as.numeric(EUcars$Drivetrain)
EUcars$Country = as.numeric(EUcars$Country)

```

```{r}
predictorMatrix <-EUcars[,c(3,4,6:11)]
responseMatrix <-EUcars[,c(2,5)]
corPredictorMatrix <- cor(predictorMatrix)
corResponseMatrix <- cor(responseMatrix)
```

## Eigen values
```{r}
#Predictor values
eigen(corPredictorMatrix)$values
plot(eigen(corPredictorMatrix)$values)

# For our predictor values using Jolliefs and Kaisers criterion we would get a intrinsic dimensional of 4 while using the inflection point would be 2. Based on this we would use a intrinsic dimensionality of 4.

#Response values
eigen(corResponseMatrix)$values
plot(eigen(corResponseMatrix)$values)

# For our Response variable Kaisers criterion would tell us to use 1 while Jolliefs tells us to use 2 and in this case the inflection point isn't helpful with our graph so based on this we are going to use a intrinsic dimensionality of 1 because that is the only way we can reduce our dimensions for Response.
```

