---
title: "European Cars"
output: html_document
date: "2025-05-8"
---

```{r setup, include=FALSE}
#install.packages("psych")
#install.packages("corrplot")
library(corrplot)
library(psych)
library(tidyverse)
library(skimr)
library(dplyr)
library(lavaan)
```

## R Markdown

```{r}
EUcars <- read_csv("car_prices.csv", na = c("", NA, "N/A"))

EUcars = EUcars |> drop_na() |> filter (Brand == "Fiat", Gearbox != "Semi-automatic", Drivetrain != "Rear") |> select(Model,Price,Kilometers,Power, Seats,Doors,Cylinders,Gearbox,Year,Drivetrain,Country)

EUcars <- replace(EUcars, EUcars == "Automatic", "0")
EUcars <- replace(EUcars, EUcars == "Manual", "1")
EUcars <- replace(EUcars, EUcars == "4WD", "1")
EUcars <- replace(EUcars, EUcars == "Front", "0")
EUcars <- replace(EUcars, EUcars == "AT", "1")
EUcars <- replace(EUcars, EUcars == "BE", "2")
EUcars <- replace(EUcars, EUcars == "DE", "3")
EUcars <- replace(EUcars, EUcars == "IT", "4")
EUcars <- replace(EUcars, EUcars == "NL", "5")

EUcars$Gearbox = as.numeric(EUcars$Gearbox)
EUcars$Drivetrain = as.numeric(EUcars$Drivetrain)
EUcars$Country = as.numeric(EUcars$Country)

SIGMA <- cov(EUcars[2:11])
```


```{r}
EQN <- "
CarUsage =~ Year + Kilometers
VehicleType =~ Gearbox + Drivetrain

Doors ~~ Power
Cylinders ~~ Doors
CarUsage ~~ Cylinders
CarUsage ~~ Country
VehicleType ~~ Power

Seats ~ CarUsage + VehicleType + Doors
Price ~ CarUsage + VehicleType + Doors
"
MOD <- sem(model = EQN, data = scale(EUcars[,2:11]))
MOD

#There are 28 degrees of freedom
```

```{r}
parameterestimates(MOD)[1:15,]
indices <- fitmeasures(MOD)
indices
```